apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: gitops-cluster
  labels:
    app.kubernetes.io/version: 1.6.0
spec:
  projectRef:
    name: gitops-project
  deploymentSpec:
    name: "gitops-cluster"
    providerSettings:
      instanceSizeName: M0
      providerName: AWS
      regionName: US_EAST_1