apiVersion: atlas.mongodb.com/v1
kind: AtlasDeployment
metadata:
  name: gitops-cluster-1
  labels:
    app.kubernetes.io/version: 1.6.0
spec:
  projectRef:
    name: sample-project
  deploymentSpec:
    name: "gitops-cluster"
    providerSettings:
      instanceSizeName: M0
      providerName: AWS
      regionName: US_EAST_1