apiVersion: atlas.mongodb.com/v1
kind: AtlasDatabaseUser
metadata:
  name: gitops-user
  labels:
    app.kubernetes.io/version: 1.6.0
spec:
  roles:
    - roleName: "readWriteAnyDatabase"
      databaseName: "admin"
  projectRef:
    name: dotlocal-project
  username: gitops-user
  passwordSecretRef:
    name: the-user-password